### PR TITLE
Quality of Life, New Feature, and Small Fixes

### PR DESCRIPTION
**Pull request by ghost**
Quality:
- Changed file encoding of .c files from ISO-8859-1 to UTF-8 / US-ANSI using iconv (for better compatibility with text editors asking for it) (Though, after analyzing the changes to the document, there is only a single character which is in ISO-8859-1 (the Spanish eñe), which is a comment and could be deleted/translated instead (tamaño -> size)).
- Deleted old readme files (english/spanish).

Features:
- Added an additional flag to makeps3iso ( -i / --output_id ) which gives the option to include the game_id in the ISO name, in the format specified by wMM ( " [game_id]" instead of "-game_id" ).
- Updated README to better reflect new project (large part coming from the new help section of makeps3iso).

Fixes:
- Added a missing new_line character to the end of the help text so that it would not "break" command line.
- Fixed what appears to be a typo in the license notice of all files (apayloadlong -> along).

### CODE REVIEW

**Comment by ghost** [comment]
@Zarh, not really related to the pull request, but I have a few questions about building an ISO with an IRD file which I haven't been able to find answer about online:
1. I've read in the BDVD specifications that Blu-Rays use a 64kb cluster size (32 sectors size 2048). So, in a 1:1 ISO, would all files be aligned to 64kb clusters?
2. Since ISO encryption is done on each sector of an ISO, does that mean that the size of the encrypted files should be the same as the size of a non encrypted file (except, of course, for any padding added at the end for alignment)?
3. There's this tool called PS3Dec (open source) which claims that it can transform a 3k3y decrypted ISO into an encrypted one using the disc key. Do you know what exactly is a 3k3y decrypted ISO? Is it just a 1:1 ISO with only the encrypted regions decrypted (thus the header, footer, and other data would match a 1:1 ISO? Does it still contain the data specifying which regions should be encrypted? If IRD support is eventually added to makeps3iso, it might be worth to only strive to make a 3k3y iso (with all files in the same offsets as the original disc, I would assume) and let PS3Dec handle encryption.
4. This is more of an idea. Aldo's ps3netsrv has "recently" added support for playing encrypted ISOs. I haven't looked at the code, but what I'm worried about is that a 3k3y ISOs (from the assumptions I made in (3)) or ODE ISOs from the new version of makeps3iso would be recognized as an encrypted ISO since it has the encryption-specifying region from the original. Of course, we would like to preserve the ability to re-encrypt the ISO to 1:1, so what I thought might be worth doing is set a flag as part of the counter for encrypted regions. So, if an encrypted ISO had 3 encrypted regions, then the count would look like 0x10000003 instead of 0x00000003 (I don't suppose an ISO will ever have more than 10 encrypted regions). So, any iso with this "flag" in this region would be detected as decrypted by any backup loader and PS3Dec (would have to modify the source code). Of course, any ISO without it would be detected as encrypted.

Edit: Do you prefer using GitHub, PSX-Place, or something else for discussing features and/or asking questions? Since this repo doesn't have an issue section, I'm not sure if asking though a pull request is really appropriate.

Edit 2: Now that I think about, instead of playing with the encrypted files counter, it might be better to modify something in the header which should be present and stay the same across games (I think 3k3y ISOs did this, but I'm not sure).

**Comment by Zarh** [comment]
**Important note** : 
makeps3iso doesn't encrypt any data, it defines some region of iso as 'encrypted' but these regions aren't really encrypted. ODE needs this to boot an iso.  The definitions of the region are inside the header, it's at the offset 0x0 of the iso. This is the only change I made to makeps3iso to support ODE.

1. No, only the encrypted region need to be 64kb aligned. With other words, the start and end offset of the encrypted region are 64kb aligned. This information come from what I saw on headers, and also from the pdf of the team cobra.
2. Yes, but I'm not sure if I understood what you meant. The encryption doesn't change the size of the file. It just 'hides' the data where it's done. It could be anywhere. Here, it's done on 'important' files (executable).
3. ps3dec is software that decrypt a iso with a REAL encryption. When you just read the data on the disc, it's really encrypted. The ISO 1:1 have region encrypted, the ps3 decrypt it 'on the fly' when it's needed. Disc dumpers like multiMAN are only able to read the raw/real/1:1 data of the disc. So, it's really encrypted. 3key/Cobra dumpers read the same data but they also add inside the iso the decryption key (offset 0xF70, i think). Then PC tools like ps3dec use the key embedded to decrypt the encrypted regions. ManaGunZ reads the raw data, and it decrypts 'on the fly' the encrypted region. I used the src of ps3dec to do the part where it decrypts.
4. No, I don't think any PC tools use the definitions of the region to detect if the iso is really encrypted or not. So, the iso built with the new makeps3iso won't be detected as encrypted by any of them. I think ps3netserv use the extension .iso.enc (i'm not sure), some other use a flag at the offset 0xF70. It still needs confirmation but I'm confident.

**Comment by ghost** [comment]
Thank you very much for the information. I was more interested in the re-encryption ability of PS3Dec rather than its decryption ability. I guess what I'm really asking is what a decrypted ISO from PS3Dec looks like, and what tools can be used to get to that point (I guess what you would call a proper decrypted ISO). I ask because I would like to be able to re-encrypt some of my dumps and match them with the hashes of 1:1 ISOs from Redump.

I'm guessing a tool like PS3-ISO-Rebuilder (and ManaGunZ?) will make a decrypted ISO (all files decrypted, aligned to their proper offsets) with its original header and footer and perhaps write the decryption key to that offset you mentioned. And then if you encrypt that ISO with PS3Dec it should come out as 1:1 (except perhaps for that offset for the decryption key, though I doubt it is added since some people claim to use PS3Dec to build Redump verifiable ISOs).

By the way, do you know any tools which are open source and are able to make an ISO using the IRD of a file? (a so-called "proper" decrypted ISO able to be encrypted to a 1:1 ISO?). All the ones I've seen are closed source and available only for Windows (like genps3iso and PS3-ISO-Rebuilder), and I was hoping there was one I could compile and use on Linux (in fact, I think makeps3iso is the only ISO creation tool which is available for *Nix systems since it is written in C and is open source).

Edit: About encryption, there are certain algorithms which will add a header or weird padding to a file which can make it actually be bigger than the original. Since the encryption is defined somewhere else in the header, I assumed that the algorithm they used would not change the size (even more so if it's run on every sector which would make it a weird procedure to decrypt), but I wasn't sure so I wanted to ask just in case.

**Comment by Zarh** [comment]
yes, you can re-encrypt with ps3dec to get the hashes of redump. I don't know if redump calculate the hashes with the embedded key, probably not... I don't have access to redump hidden threads, ask them :)

About the tools, I don't know any, sry.

**Comment by ghost** [comment]
As a practice project, I'll try to create a program in C which is able to rebuild an ISO using an IRD file. It should be less complicated than makeps3iso, since I'm basically just reading offsets and writing to it. I'll probably use some source from MGZ and ird_tools for extracting IRDs, reading the hashes, and reading the headers of real ISOs. I also want to add a way for the program to keep a local cache of disc updates which it can then use to rebuild ISOs which do not have them. I am not 100% sure of the structure that "proper" decrypted ISOs have, but I'll analyze a few decrypted ISOs from MGZ for that purpose (if I understood properly what MGZ does behind the scenes) and read through the Blu-Ray specifications about the data section of the disc.

It may take me a while as I'm quite new to c programming, but I'll try to integrate these changes into your fork of makeps3iso. In fact, I also want to merge all of Estwald's tools into 1, to avoid repeated code and for a better user experience. Maybe I'll even integrate PS3Dec (though, it's not really necessary to be honest). I'll get back to you on this.

**Comment by Zarh** [comment]
It was my intention in the first place to merge everything in 1 exe, something similar to orbis-cmd-pub with different command. It would be named simply ps3iso-utils.exe :)

**Comment by ghost** [comment]
>     (I don't suppose an ISO will ever have more than 10 encrypted regions).

Never mind, I just dumped COD 4 with ManaGunZ, and discovered that it has more than 100 different encrypted regions (I think the developers encrypted every single file in the USRDIR directory separately). Since every encrypted region must be odd, there is a lot of padding in the disc, so much so that a "proper" encrypted ISO (made with MGZ) is 2gb bigger than a JB folder dump or an ISO made with makeps3iso.

**Comment by Zarh** [comment]
- It looks like every file in encrypted region is 32sector aligned. Ok,  genps3iso does it, too. it doesn't really surprise me. It faster like that. Because the ps3 won't decrypt unnecessary sector.
- Lot of games encrypt the whole USRDIR, most of them actually. Also, not a surprise.
- But the weirdest are the **empty** plain regions between the encrypted. This is absolutely not due to the padding. it explains why there is so many region. **My guess is**: it's perhaps a way to put the files at the outside of disc when it's burned. Because files at the outward of the disc can be read faster than those from the center. I don't have any other explanation about these huge gap of empty plain region.

This is the weirdest header I ever see, nice catch :)

**Pull request merged**
